spring:
  datasource:
    url: jdbc:h2:mem:testdb
  main:
    allow-circular-references: true

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none